print("What is your name human?")
name= input()
print("How old are you (in years?)")
age= int(input())
print("How tall are you (in metres?)")
height= float(input())
print("How much do you weight (in kilograms?)")
weight= float(input())
# bmi= weight/(height*height)
bmi= weight/(height**2)
print("{} you are {} years old and your bmi is {:.2f}.".format(name, age, bmi))